services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoppinglist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/app/src
    command: npm run start
    depends_on:
      - postgres

  app-client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    command: npm run start
    depends_on:
      - app-server

volumes:
  postgres_data:
